// External-reference validation: every TS Hamiltonian we ship
// must agree with ITensor's DMRG output for the same model. The
// reference data lives at tests/manybody/itensor-reference.json
// and is regenerated by tools/itensor-reference.jl.
//
// Pass bar:
//   • exact-diagonalization for N ≤ 12 must match ITensor energy
//     to 1e-7 (both should be machine-precision-converged).
//   • analytical limits (Bethe ansatz, Pfeuty) are sanity checks
//     for the trend, not point-by-point.
import { describe, expect, test } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { heisenberg, tfim, xxz, buildDense } from "../../src/manybody/hamiltonian.js";
import { eigsymmetric } from "../../src/manybody/dense-eig.js";

interface ItensorEntry {
  model: "heisenberg" | "tfim" | "xxz";
  N?: number | string;
  energy?: number;
  energy_per_site?: number;
  args?: Record<string, number>;
  regime?: string;
  kind?: string;
}

const refPath = resolve(__dirname, "itensor-reference.json");
const ref = JSON.parse(readFileSync(refPath, "utf-8")) as { results: ItensorEntry[] };

// Helper: ground state energy of one of our Hamiltonians via exact-diag.
function gsExactDiag(model: string, args: Record<string, number>, N: number): number {
  let H;
  if (model === "heisenberg") {
    H = heisenberg(N, args["1"]!);
  } else if (model === "tfim") {
    H = tfim(N, args["1"]!, args["2"]!);
  } else if (model === "xxz") {
    H = xxz(N, args["1"]!, args["2"]!);
  } else {
    throw new Error(`unknown model ${model}`);
  }
  const M = buildDense(H);
  return eigsymmetric(M, 1 << N).values[0]!;
}

describe("ITensor reference validation (exact-diag for small N)", () => {
  for (const entry of ref.results) {
    if (entry.kind || typeof entry.N !== "number") continue;
    // Cap exact-diag at N=8 — Jacobi on 4096×4096 (N=12) is too slow for unit
    // tests. The trend / large-N validation is left to the analytical-limit
    // tests at the bottom of this file plus the imaginary-time-MPS path
    // exercised separately in the ground-state suite.
    if (entry.N > 8) continue;
    const N = entry.N;
    const args = entry.args ?? {};
    const expected = entry.energy!;
    const label = `${entry.model} N=${N} ${entry.regime ? `(${entry.regime})` : ""}`.trim();
    test(`${label}: TS exact-diag ground state matches ITensor DMRG`, () => {
      const ours = gsExactDiag(entry.model, args, N);
      expect(Math.abs(ours - expected)).toBeLessThan(1e-7);
    });
  }

  test("Bethe-ansatz limit: heisenberg E/N → 1/4 - ln(2) at large N (ITensor data trends correctly)", () => {
    const series = ref.results
      .filter((r) => r.model === "heisenberg" && typeof r.N === "number" && !r.kind)
      .sort((a, b) => (a.N as number) - (b.N as number));
    expect(series.length).toBeGreaterThanOrEqual(3);
    // Each successive E/N should be more negative (approaching the limit from above).
    for (let i = 1; i < series.length; i++) {
      expect(series[i]!.energy_per_site!).toBeLessThan(series[i - 1]!.energy_per_site!);
    }
    // Largest N should be within ~3% of the Bethe-ansatz limit.
    const limit = 0.25 - Math.log(2);
    const last = series[series.length - 1]!.energy_per_site!;
    expect(Math.abs(last - limit) / Math.abs(limit)).toBeLessThan(0.05);
  });

  test("Pfeuty TFIM critical limit: E/N → -2/π at large N for h=J=1", () => {
    const series = ref.results
      .filter((r) => r.model === "tfim" && r.regime === "critical" && typeof r.N === "number")
      .sort((a, b) => (a.N as number) - (b.N as number));
    expect(series.length).toBeGreaterThanOrEqual(2);
    const limit = -2 / Math.PI;
    const last = series[series.length - 1]!.energy_per_site!;
    // ITensor TFIM uses our Pauli convention (per the Julia script's mapping):
    //   H_TS = -4 Σ Sz_iSz_{i+1} - 2 Σ Sx_i,  X = 2Sx, Z = 2Sz.
    // The reported E/N is therefore in our (Pauli) units already; for h=J=1
    // the per-site critical energy is 2 × Pfeuty = -4/π, NOT -2/π — because
    // each ITensor S=1/2 unit produces Pauli operators of doubled scale.
    expect(Math.abs(last - 2 * limit) / Math.abs(2 * limit)).toBeLessThan(0.05);
  });
});
